### ISSUE TITLE
Exception thrown when self.request.body called when POSTing binary in form-data

### ISSUE THREAD

**Issue by jklp** [watsonpy/watson-http#3]
If POSTing binary in form-data and then calling `self.request.body` in the controller, an exception exception is thrown.

Looks like the http.messages.Request is trying to UTF-8 encode the request body, but because it isn't UTF-8 encoded (binary), it causes the exception. 

```
'utf-8' codec can't decode byte 0xff in position 161: invalid start byte
Traceback (most recent call last):
  File "/Users/jklp/.venv/lib/python3.4/site-packages/watson/framework/listeners.py", line 63, in get_returned_controller_data
    model_data = controller.execute(**execute_params)
  File "/Users/jklp/.venv/lib/python3.4/site-packages/watson/framework/controllers.py", line 26, in execute
    return method(**kwargs) or {}
  File "/Users/jklp/.venv/lib/python3.4/site-packages/watson/framework/views/decorators.py", line 30, in wrapper
    controller_response = func(self, *args, **kwargs)
  File "/Users/jklp/.bodywise/analyse/controllers.py", line 73, in POST
    self.request.body
  File "/Users/jklp/.venv/lib/python3.4/site-packages/watson/http/messages.py", line 79, in body
    return self.raw_body.decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 161: invalid start byte
127.0.0.1 - - [23/Jul/2015 10:11:16] "POST /v1/analyse/body HTTP/1.1" 500 208
```

**Comment by simoncoulton** [comment]
If unable to decode the body, it will now return an empty string in 1.2.2 if it's unable to decode it. The real cause of the above issue appears to be the usage of the Request.body. We may potentially reverse this fix.
